In [1]:
import numpy as np

In [2]:
#Define an array 

my_first_arr = np.array([1,2,3])
my_first_arr

array([1, 2, 3])

In [3]:
my_first_arr.shape

(3,)

In [4]:
type(my_first_arr)

numpy.ndarray

In [5]:
#Define another array - multidimensional

my_second_arr = np.array([[-1, 2.5, 3], [-0.7, 4, 100]])
my_second_arr

array([[ -1. ,   2.5,   3. ],
       [ -0.7,   4. , 100. ]])

In [6]:
my_second_arr.shape

(2, 3)

In [7]:
#Define another array - multidimensional

my_third_arr = np.array([[[-1, 2.5, 3], [-0.7, 4, 100]], [[-1, 2.5, 3], [-0.7, 4, 101]]])
my_third_arr

array([[[ -1. ,   2.5,   3. ],
        [ -0.7,   4. , 100. ]],

       [[ -1. ,   2.5,   3. ],
        [ -0.7,   4. , 101. ]]])

In [8]:
my_third_arr.ndim

3

In [9]:
my_third_arr.shape

(2, 2, 3)

In [10]:
my_second_arr

array([[ -1. ,   2.5,   3. ],
       [ -0.7,   4. , 100. ]])

In [11]:
#simplest mathematical operation

my_second_arr + 10

array([[  9. ,  12.5,  13. ],
       [  9.3,  14. , 110. ]])

In [12]:
#simplest mathematical operation

my_second_arr - 10

array([[-11. ,  -7.5,  -7. ],
       [-10.7,  -6. ,  90. ]])

In [13]:
#simplest mathematical operation

my_second_arr * 10

array([[ -10.,   25.,   30.],
       [  -7.,   40., 1000.]])

In [16]:
my_second_arr

array([[ -1. ,   2.5,   3. ],
       [ -0.7,   4. , 100. ]])

In [18]:
#sum two matrices
my_second_arr + my_second_arr

array([[ -2. ,   5. ,   6. ],
       [ -1.4,   8. , 200. ]])

In [20]:
my_first_arr

array([1, 2, 3])

In [19]:
#another operation

my_second_arr + my_first_arr

array([[  0. ,   4.5,   6. ],
       [  0.3,   6. , 103. ]])

In [21]:
# shape of the array

my_second_arr.shape

(2, 3)

In [22]:
my_arr = np.array([[1, 4, 7], [2, 8, 3], [10, 1, 6]])
my_arr

array([[ 1,  4,  7],
       [ 2,  8,  3],
       [10,  1,  6]])

#### MEDIAN

In [38]:
#along rows
np.median(my_arr, axis = 1)

array([4., 3., 6.])

In [23]:
#along column
np.median(my_arr, axis = 0)

array([2., 4., 6.])

#### MEAN

In [24]:
#along rows
np.mean(my_arr, axis = 1)

array([4.        , 4.33333333, 5.66666667])

#### RESHAPE

In [25]:
my_arr

array([[ 1,  4,  7],
       [ 2,  8,  3],
       [10,  1,  6]])

In [27]:
my_arr.reshape(9, 1)

array([[ 1],
       [ 4],
       [ 7],
       [ 2],
       [ 8],
       [ 3],
       [10],
       [ 1],
       [ 6]])

In [28]:
my_arr.reshape(1, 9)

array([[ 1,  4,  7,  2,  8,  3, 10,  1,  6]])

In [46]:
# create an array of zeros of a particular shape

np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
# create a 2d-array of zeros of a particular shape

np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
# create an array of ones of a particular shape

np.ones(3)

array([1., 1., 1.])

In [20]:
# Range function

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# Range function

np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [24]:
# Data types for ndarrays

my_arr = np.array([1, 2, 3])
my_arr

array([1, 2, 3])

In [25]:
my_arr.dtype

dtype('int64')

In [26]:
my_arr = np.array([1, 2, 3], dtype = np.float32)
my_arr

array([1., 2., 3.], dtype=float32)

#### Indexing and slicing

In [29]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
#access first element

arr[0]

0

In [31]:
#access first element

arr[-1]

9

In [32]:
#slice an array

arr[4:6]

array([4, 5])

In [27]:
#an interesting functionality
print('Array Before : {}'.format(arr))
arr[5:8] = -10
print('Array After : {}'.format(arr))

Array Before : [0 1 2 3 4 5 6 7 8 9]
Array After : [  0   1   2   3   4 -10 -10 -10   8   9]


In [28]:
#Lets create a copy of an array

arr_copy = arr

arr_copy

array([  0,   1,   2,   3,   4, -10, -10, -10,   8,   9])

In [29]:
arr

array([  0,   1,   2,   3,   4, -10, -10, -10,   8,   9])

In [30]:
#make some changes to arr_copy

arr_copy[1] = 100
arr_copy

array([  0, 100,   2,   3,   4, -10, -10, -10,   8,   9])

In [31]:
arr

array([  0, 100,   2,   3,   4, -10, -10, -10,   8,   9])

Any change in copy is reflected in the original array

In [33]:
#to avoid any change in original

arr_copy = arr.copy()

arr_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr_copy[0] = -100
arr_copy

array([-100,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [36]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
#Lets access a 2d array

arr2d = np.array([[1, 2, 3],[10, 20, 30]])
arr2d

array([[ 1,  2,  3],
       [10, 20, 30]])

In [38]:
arr2d[1, 1] #arr2d[1][1]

20

In [39]:
arr2d[0, 0]

1

In [38]:
#Lets access a 3d array

arr3d = np.array([[[1, 2, 3],[10, 20, 30]], [[7, 8, 9], [70, 80, 90]]])
arr3d

array([[[ 1,  2,  3],
        [10, 20, 30]],

       [[ 7,  8,  9],
        [70, 80, 90]]])

In [39]:
arr3d[1, 1, 1]

80

In [40]:
arr3d[1, 1, :2]

array([70, 80])

In [47]:
#updating using slicing
arr3d[1, 1, :2] = 0
arr3d

array([[[ 1,  2,  3],
        [10, 20, 30]],

       [[ 7,  8,  9],
        [ 0,  0, 90]]])

#### Array Generators

In [42]:
# an array of linear spaced values
np.linspace(0,10,9)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [44]:
#Boolean indexing

arr_of_names = np.array(['Biden', 'Trump', 'Johnson', 'Biden', 'Biden', 'Tom', 'Trump'])
arr_of_names

array(['Biden', 'Trump', 'Johnson', 'Biden', 'Biden', 'Tom', 'Trump'],
      dtype='<U7')

In [45]:
arr_of_names == 'Biden'

array([ True, False, False,  True,  True, False, False])

In [46]:
# filtering the array
arr_of_names[arr_of_names=='Biden']

array(['Biden', 'Biden', 'Biden'], dtype='<U7')

In [51]:
arr_of_ages = np.array([65, 60, 62, 64, 63, 67, 61])

arr_of_ages[arr_of_names=='Biden']

array([65, 64, 63])

In [52]:
arr_of_ages[arr_of_names!='Biden']

array([60, 62, 67, 61])

In [59]:
#filter and replace
arr_of_names[arr_of_names=='Biden'] = 'Joe'

In [60]:
arr_of_names

array(['Joe', 'Trump', 'Johnson', 'Joe', 'Joe', 'Tom', 'Trump'],
      dtype='<U7')

In [47]:
#transpose - change rows into columns and vice-versa
my_arr

array([[ 1,  4,  7],
       [ 2,  8,  3],
       [10,  1,  6]])

In [48]:
my_arr.T

array([[ 1,  2, 10],
       [ 4,  8,  1],
       [ 7,  3,  6]])

In [54]:
#Random Number Generation
#Generate any random integer in a given range

np.random.randint(500)

488

In [57]:
np.random.randint(10)

0

In [75]:
np.random.rand(3)

array([0.87847984, 0.79007262, 0.63040688])

In [76]:
np.random.rand(10)

array([0.03376188, 0.53214033, 0.22704287, 0.40464701, 0.15637612,
       0.42218984, 0.13422903, 0.91536139, 0.89833147, 0.36112443])

In [77]:
np.random.rand(2,2)

array([[0.38103678, 0.94577907],
       [0.22981977, 0.19649958]])

In [78]:
np.random.randint(100, size=(10))

array([ 7, 29, 31, 22, 92, 88,  5, 80, 63,  5])

In [63]:
#Randomly chooses
np.random.choice(['Tom', 'John', 'Jack', 'Jill', 'Mary', 'Johnson'], size = (2))

array(['Tom', 'John'], dtype='<U7')

In [64]:
#Known functions

my_arr = np.arange(26)
my_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [65]:
# taking square root
np.sqrt(my_arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        ])

In [66]:
# applying log
np.log(my_arr)

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
       3.21887582])

In [67]:
# rounding to next integer
np.ceil(np.sqrt(my_arr))

array([0., 1., 2., 2., 2., 3., 3., 3., 3., 3., 4., 4., 4., 4., 4., 4., 4.,
       5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [127]:
#previous integer
np.floor(np.sqrt(my_arr))

array([0., 1., 1., 1., 2., 2., 2., 2., 2., 3., 3., 3., 3., 3., 3., 3., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 5.])

In [80]:
#compute pair wise maximum in both arrays
arr1 = np.array([-1, 0, 10])
arr2 = np.array([3, -10, -20])

np.maximum(arr1, arr2)

array([ 3,  0, 10])

#### Setting a seed

In [82]:
# run it n number of times and observe change in output
np.random.seed(100)

np.random.randint(500)

8

In [77]:
# run it n number of times and observe change in output
np.random.randint(500)

156

#### Ravel

In [91]:
np.array([[1, 4, 10], [100, 200, 300]])

array([[  1,   4,  10],
       [100, 200, 300]])

In [95]:
#flattening in row major order
np.ravel(np.array([[1, 4, 10], [100, 200, 300]]), order = 'C')

array([  1,   4,  10, 100, 200, 300])

In [84]:
#flattening in column major order
np.ravel(np.array([[1, 4, 10], [100, 200, 300]]), order = 'F')

array([  1, 100,   4, 200,  10, 300])

FOR MORE INFORMATION VISIT https://numpy.org/doc/stable/user/absolute_beginners.html